name: Pipeline CI/CD projet m1meldinodeapp
on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: td-app
  REPO: ghcr.io

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps: 
    
      - name: recupérer le code source
        uses: actions/checkout@v4

      - name: lancer les tests
        run: ls -lah
    
  build:
    needs: test
    name: build and push 
    runs-on: ubuntu-latest
    steps: 
    
      - name: recupérer le code source
        uses: actions/checkout@v4

      - name: build de l'image docker
        run: docker build -t ${{env.IMAGE_NAME}} .

      - name: run l'image docker
        run: docker run -d -p 3000:3000 ${{env.IMAGE_NAME}}

      - name: taguer en version courante 
        run: "docker tag ${{env.IMAGE_NAME}}:1.0 ${{env.REPO}}/${{ github.actor }}/${{env.IMAGE_NAME}}:1.0"
      - name: taguer en version latest
        run: "docker tag ${{env.IMAGE_NAME}}:latest ${{env.REPO}}/${{ github.actor }}/${{env.IMAGE_NAME}}:latest"
        name : connexion a GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{env.REPO}}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKENCICD }}
      - name: push de l'image v1.0
        run: "docker push ${{env.REPO}}/${{ github.actor }}/${{env.IMAGE_NAME}}:1.0"
      - name: push de l'image latest
        run: "docker push ${{env.REPO}}/${{ github.actor }}/${{env.IMAGE_NAME}}:latest"